config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :users
  resources :issues

  get 'students/index'
  get 'mentors/index'
  get 'administrators/index'
  get 'dispatcher/send_to'
  get 'issues/set_status'
  #drag
  get '/issue/:id/date_status', to: 'issues#date_status', as: :date_status


  #Api
   namespace :api do
    namespace :v1 do
      resources :users
    end
  end

  root 'dispatcher#send_to'
end

app/views/partials/_calendar.html.haml
#calendar
    .row.bg-light.p-4.m-3.border-dashed
        - if @user.role == "student"
            =content_tag :btn, class: 'newissue rounded-circle border-dashed mr-2 text-center align-self-center p-2', "data-target" => "#newissue", "data-toggle" => "modal" do
                =fa_icon "plus"
        - if @user.role == "mentor"
            =link_to issues_path, class: 'newissue rounded-circle border-dashed mr-2 text-center align-self-center p-2' do
                =content_tag :btn do
                    =fa_icon "search-plus"
        - if Issue.current(@user).count == 0 && @user.role == "student"
            .mr-2.animated.infinite.tada.nowrap
                =fa_icon "arrow-left 3x"
            .animated.infinite.pulse.mt-3.ml-2.font-weight-bold
                CREATE NEW ISSUE!
        - if Issue.mentor(@user).count == 0 && @user.role == "mentor"
            .mr-2.animated.infinite.tada.nowra
                =fa_icon "arrow-left 3x"
                
            .animated.infinite.pulse.mt-3.ml-2.font-weight-bold
                START HELPING LOOKING FOR ISSUES!
        -if @user.role == "student"                
            -Issue.current(@user).no_appointment.each do |issue|
                = content_tag :div, id: 'yes-drop', class: 'drag-drop rounded-circle tap', issueid: issue.id, data: { draggable: true, url: date_status_url(issue)} do
                    %img.rounded-circle{:height => "41", :width => "41" ,:src => "https://robohash.org/#{issue.user.username}.png?size=258x180"}/ 

            -if Issue.current(@user).valid.count == 0 && Issue.current(@user).count > 0
                .pl-2.mr-2.animated.infinite.tada.nowrap
                    =fa_icon "arrow-down 3x"
                .animated.infinite.pulse.font-weight-bold.float-right.mt-3.ml-2
                    drag issue!
                    
        -if @user.role == "mentor"                
            -Issue.mentor(@user).no_appointment.each do |issue|
                = content_tag :div, id: 'yes-drop', class: 'drag-drop rounded-circle tap', issueid: issue.id, data: { draggable: true, url: date_status_url(issue)} do
                    %img.rounded-circle{:height => "41", :width => "41" ,:src => "https://robohash.org/#{issue.user.username}.png?size=258x180"}/ 

                        
            -if Issue.mentor(@user).valid.count == 0 && Issue.mentor(@user).count > 0
                .pl-2.mr-2.animated.infinite.tada.nowrap
                    =fa_icon "arrow-down 3x"
                .animated.infinite.pulse.font-weight-bold.float-right.mt-3.ml-2
                    drag issue! 

    .row.m-2
        .col.p-3
        -@weekday.map do |date|
            .col.border.bg-info.p-3
                =date.strftime("%a, %d %b")
                -if date == @today
                    .badge.badge-success   
                        today
        
    .row.m-2
        .col.d-flex-flex-column.p-0
            -@hour.map do |time|
                .col.border.p-4
                    =time

        - 7.times do |x|
            .col.d-flex.flex-column.p-0
                - 11.times do |y|
                    =content_tag :date, class: "dropzone col border p-4 acepted_value", id: "acepted_value", date: @weekday[x], interval:@hour[y], index: y + x * 11 do
                        -if @user.role == "student"
                            -Issue.current(@user).appointment(@weekday[x],@hour[y]).each do |issue|	     
                                = content_tag :div,id: 'yes-drop',class: 'drag-drop rounded-circle',data: { draggable: true, url: date_status_url(issue) } do
                                    %img.rounded-circle{:height => "45", :width => "45" ,:src => "https://robohash.org/#{issue.user.username}.png?size=258x180"}/ 
                        - else                           
                            -Issue.mentor(@user).appointment(@weekday[x],@hour[y]).each do |issue|	     
                                = content_tag :div,id: 'yes-drop',class: 'drag-drop rounded-circle',data: { draggable: true, url: date_status_url(issue) } do
                                    %img.rounded-circle{:height => "45", :width => "45" ,:src => "https://robohash.org/#{issue.user.username}.png?size=258x180"}/ 
                             

app/views/partials/_cards.html.haml
-if @issues.length == 0
  = render partial: '/partials/modal_issue_empty'
- else
  - @issues.each do |issue|
    .card{:style => "width: 100%"}
      .card-header
        %h5.card-title 
          = issue.title
      .card-body
        .row
          .col{:style => "text-align:center"}
            %h5 Name
          .col{:style => "text-align:center"}
            %h5 Date
          .col{:style => "text-align:center"}
            %h5 Reward
          .col{:style => "text-align:center"}
            %h5 Status

        .row
          .col{:style => "text-align:center"}
            - if issue.user.id == current_user.id
              %p{:style => "color:purple"}
                Yours
            -else
              %p
                #{issue.user.name}, #{issue.user.lastname}
          .col{:style => "text-align:center"}
            - if issue.date?
              = issue.date
          .col{:style => "text-align:center"}
            = issue.incentive
          .col{:style => "text-align:center"}
            - if issue.status
              - if current_user.email == issue.mentor
                %p{:style => "color:purple"} 
                  Assigned to you
              - else
                %p{:style => "color:red"} 
                  Assigned
            - else
              %p{:style => "color:green"}
                To be assigned
        %p.card-text 
          %p
            = h truncate(issue.description, :length => 238)
          .text-right
            %div
              - role = current_user.role
              = render partial: '/partials/modal_issue_show', locals: {issue: issue}
              - if role == 'admin'
                -# Modal
                -# = render partial: '/partials/modal_issue_edit', locals: {issue: issue}
                = link_to 'Edit', edit_issue_path(issue), class: "btn btn-info"
                = link_to 'Destroy', issue, remote: true, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"
              - elsif role == 'mentor'
                - if issue.status == false
                  = link_to 'Accept', issue, remote: true, method: :put, class: "btn btn-primary"
                - elsif current_user.email == issue.mentor
                  = link_to 'Unassign', issue, remote: true, method: :put, data: { confirm: '¿Cancel?' }, class: "btn btn-danger"
              - else 
                - if current_user.id == issue.user.id
                  -# Modal
                  -# = render partial: '/partials/modal_issue_edit', locals: {issue: issue}
                  = link_to 'Edit', edit_issue_path(issue), class: "btn btn-info" 
                  = link_to 'Destroy', issue, remote: true, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"
    %br
  %br
                

app/views/partials/_cards_users.html.haml
%br
.row
  - @users.each do |user|
    .card.col-3
      %img.card-img-top{:alt => "Card image cap", :src => "https://robohash.org/#{user.username}.png?size=258x180"}/
      .card-body
        %h5.card-title 
          = user.username
        %p.card-text 
          = h truncate(user.email, :length => 25)
        %p.card-text
          - if user.role == 'admin'
            %p{:style => "color:purple"} ADMIN
          - elsif user.role == 'mentor'
            %p{:style => "color:blue"} Mentor
          - else
            %p{:style => "color:teal"} Student
        %small.text-muted 
          = user.created_at.strftime("%-d %bzo %Y")
        .col
          = render partial: '/partials/modal_user_show', locals: {user: user}
          -# Modal
          -# = render partial: '/partials/modal_user_edit', locals: {user: user}
          = link_to 'Edit', edit_user_path(user), class: "btn btn-sm btn-info"
          = link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm"
%br
          
       

app/views/partials/_modal_issue_edit.html.haml
%button.btn.btn-info{"data-target" => "#modal_edit#{issue.id}", "data-toggle" => "modal", :type => "button"}
  Edit 
.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "modal#{issue.id}", :role => "dialog", :tabindex => "-1", :id => "modal_edit#{issue.id}"}
  .modal-dialog.modal-lg{:role => "document"}
    = form_for issue, remote:true do |f|
      .modal-content
        .modal-header
          %h3#exampleModalLabel.modal-title Editando solicitud
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
        .modal-body
          .form-row
            .form-group.col-12
              = f.text_field :title, placeholder: "Kind of support", class: "form-control", maxlength: "60"
            .form-group.col-12
              = f.text_area :description, placeholder: "Details of the support you need", class: "form-control"
            .form-group.col-8
              = f.text_field :incentive, placeholder: "Reward: e.g. $2, braekfast, hook", class: "form-control", maxlength: "20"
            .form-group.col-4
              = f.select :interval, :"7:00am" => "7:00am", :"8:00am" => "8:00am", :"9:00am" => "9:00am", :"10:00am" => "10:00am",:"11:00am" => "11:00am", :"12:00pm" => "12:00pm", :"1:00pm" => "01:00am", :"2:00pm" => "2:00am",:"3:00pm" => "3:00pm", :"4:00pm" => "4:00pm", :"5:00pm" => "5:00pm" 

            .form-group.col-12.text-left
              = f.label :date
              = f.date_field :date, class: "form-control", min: Time.now, max: Time.now + 604800
          .form-row
            .col-6.text-left
              %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} close    
            .col-6.text-right
              = f.submit 'Save', class: "btn btn-primary"
            

app/views/partials/_modal_issue_empty.html.haml
- if current_user.role == 'student'
  %div.mt-5.btn-link.col-12.text-right{:style => "text-decoration:none"}
    %h4{:style => "color:teal"}
      Click here!
      = fa_icon "arrow-right 1x"
    .card-body.text-center
      %p
        = fa_icon "edit 5x"
      %h2{:style => "color:teal"} You don't have any support request yet?
      %h5.text-muted Click on 'New support request' button, to create a new request in order to be seen by mentors
      %h5.text-muted The support request will be evaluated by our community of mentors
- elsif current_user.role == 'mentor'
  %div.mt-5.btn-link.col-12.text-right{:style => "text-decoration:none"}
    %h4{:style => "color:teal"}
      Click here!
      = fa_icon "arrow-right 1x"
    .card-body.text-center
      %p
        = fa_icon "edit 5x"
      %h2{:style => "color:teal"} You don't have any support request accepted yet?
      %h5.text-muted 
        Click on 'All support request' button, help some 
        %b Juniors 
        to be "Web Developers"
      %h5.text-muted  Teaching we learn...
- else
  %div.mt-5.btn-link.col-12.text-left{:style => "text-decoration:none"}
    %h4{:style => "color:teal"}
      = fa_icon "arrow-left 1x"
      Click here!
    .card-body.text-center
      %p
        = fa_icon "smile-o 5x"
      %h2{:style => "color:teal"} You should come back later
      %h5.text-muted It seems nobody needs support so far

app/views/partials/_modal_issue_new.html.haml
-# / Button
-# %button.btn.btn-primary{"data-target" => "#newissue", "data-toggle" => "modal", :type => "button"}
-#   New Support Request
/ Modal

#newissue.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-lg{:role => "document"}
    %p#notice= notice
    = @var
    = form_for @issue, remote:true do |f|
      .modal-content
        .modal-header
          %h3#exampleModalLabel.modal-title New support request
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
        .modal-body
          .form-row
            .form-group.col-12
              = f.text_field :title, placeholder: "Kind of support", class: "form-control", maxlength: "60"
            .form-group.col-12
              = f.text_area :description, placeholder: "Details of the support you need", class: "form-control"
            .form-group.col-12
              = f.text_field :incentive, placeholder: "Reward: e.g. $2, braekfast, hook", class: "form-control", maxlength: "20"
          .form-row
            .col-6.text-left
              %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} close    
            .col-6.text-right
              = f.submit 'Save', class: "btn btn-primary"
            

app/views/partials/_modal_issue_show.html.haml
%button.btn.btn-secondary{"data-target" => "#modal_show#{issue.id}", "data-toggle" => "modal", :type => "button"}
  Show
.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "modal_show#{issue.id}", :role => "dialog", :tabindex => "-1", :id => "modal_show#{issue.id}"}
  .modal-dialog.modal-lg{:role => "document"}
    .modal-content
      .modal-header
        %h4#exampleModalLabel.modal-title.text-center
          = issue.title
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        .row.text-left
          .col-6
            %h5 User
            %span
              = issue.user.username
          .col-6
            %h5 Date
            - if issue.date?
              = issue.date
            - else
              %p{:style => "color:gray"}
                Date non assigned
          .col-6
            %h5 Reward
            = issue.incentive
          .col-6
            %h5 Meeting time
            = issue.interval
          .col-6
            %h5 Status
            - if issue.status
              - if current_user.email == issue.mentor
                %p{:style => "color:purple"} 
                  Assigned to you
              - else
                %p{:style => "color:red"} 
                  Assigned to #{issue.mentor}
            - else
              %p{:style => "color:green"}
                To be assigned
          .col-12
            %p
              = issue.description
        .row
          .col-6.text-left
            %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} close
          .col-6.text-right
            %div
              - role = current_user.role
              - if role == 'admin'
                -# = render partial: '/partials/modal_issue_edit', locals: {issue: issue}
                = link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"
              - elsif role == 'mentor'
                - if issue.status == false
                  = link_to 'Accept', issue, method: :put, class: "btn btn-primary"
                - elsif current_user.email == issue.mentor
                  = link_to 'Unassign', issue, method: :put, data: { confirm: '¿Cancel?' }, class: "btn btn-danger"
              - else 
                - if current_user.id == issue.user.id
                  -# = render partial: '/partials/modal_issue_edit', locals: {issue: issue}
                  = link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"
        

          

app/views/partials/_modal_user_edit.html.haml
%button.btn.btn-info.btn-sm{"data-target" => "#modal_edit#{user.id}", "data-toggle" => "modal", :type => "button"}
  Edit User
.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "modal#{user.id}", :role => "dialog", :tabindex => "-1", :id => "modal_edit#{user.id}"}
  .modal-dialog.modal-lg{:role => "document"}
    = form_for user, remote:true do |f|
      .modal-content
        .modal-header
          %h3#exampleModalLabel.modal-title Editing user
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
        .modal-body
          .form-row
            .form-group.col-md-4
              = f.label :Email
              = f.email_field :email, placeholder: "email@exampĺe.com", class: "form-control"
            .form-group.col-md-4
              = f.label :Password
              = f.password_field :password, placeholder: "your secret password", class: "form-control", minlength: "4"
            .form-group.col-md-4
              .field
                = f.label :rol
              .btn-group.btn-group-toggle{"data-toggle" => "buttons"}
                %label.btn.btn-secondary
                  = f.radio_button :role, 'student', checked: true
                  student
                %label.btn.btn-secondary
                  = f.radio_button :role, 'mentor'
                  mentor
                %label.btn.btn-secondary
                  = f.radio_button :role, 'admin'
                  admin
          .form-row
            .form-group.col-md-4
              = f.label :Nombre
              = f.text_field :name, placeholder: "e.g. Daniel", class: "form-control"
            .form-group.col-md-4
              = f.label :Apellido
              = f.text_field :lastname, placeholder: "e.g. Hernandez", class: "form-control"
            .form-group.col-md-4
              = f.label :"Username" 
              = f.text_field :username, placeholder: "danielHernandez", class: "form-control", maxlength: "16", minlength: "4"
          .form-group
            = f.label :"Programming Skills"
            = f.text_area :knowledge, placeholder: "e.g. rails, ruby, react", class: "form-control"
          %br
          .action.text-right
            = f.submit 'Save', class: "btn btn-md btn-success"


                  

            

app/views/partials/_modal_user_new.html.haml
%button.btn.btn-primary.mt-3{"data-target" => "#modal_new_user", "data-toggle" => "modal", :type => "button"}
  New User
.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "modal", :role => "dialog", :tabindex => "-1", :id => "modal_new_user"}
  .modal-dialog.modal-lg{:role => "document"}
    = form_for @user, remote:true do |f|
      .modal-content
        .modal-header
          %h3#exampleModalLabel.modal-title Nuevo usuario
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
        .modal-body
          .form-row
            .form-group.col-md-4
              %p{"data-placement" => "top", "data-toggle" => "tooltip", :style => "cursor:pointer", :title => "El email debe ser unico y debe tener minimo 8 caracteres"}
                Email
              = f.email_field :email, placeholder: "email@example.com", class: "form-control"
            .form-group.col-md-4
              %p{"data-placement" => "top", "data-toggle" => "tooltip", :style => "cursor:pointer", :title => "minumum 4 characters"}
                Password
              = f.password_field :password, placeholder: "your secret password", class: "form-control", minlength: "4"
            .form-group.col-md-4
              .field
                %p{"data-placement" => "top", "data-toggle" => "tooltip", :style => "cursor:pointer", :title => "Default role: student"}
                  Role
              .btn-group.btn-group-toggle{"data-toggle" => "buttons"}
                %label.btn.btn-secondary
                  = f.radio_button :role, 'student', checked: true
                  student
                %label.btn.btn-secondary
                  = f.radio_button :role, 'mentor'
                  mentor
                %label.btn.btn-secondary
                  = f.radio_button :role, 'admin'
                  admin
          .form-row
            .form-group.col-md-4
              %p{"data-placement" => "top", "data-toggle" => "tooltip", :style => "cursor:pointer", :title => "Minimum 3 characters"}
                Name
              = f.text_field :name, placeholder: "e.g. Daniel", class: "form-control"
            .form-group.col-md-4
              %p{"data-placement" => "top", "data-toggle" => "tooltip", :style => "cursor:pointer", :title => "Minimum 3 characters"}
                Lastname
              = f.text_field :lastname, placeholder: "e.g. Hernandez", class: "form-control"
            .form-group.col-md-4
              %p{"data-placement" => "top", "data-toggle" => "tooltip", :style => "cursor:pointer", :title => "Must be unique and have 4 caracters at least"}
                Username
              = f.text_field :username, placeholder: "danielHernandez", class: "form-control", minlength: "4", maxlength: "16"
          .form-group
            Programming Skills
            = f.text_area :knowledge, placeholder: "e.g. rails, ruby, react", class: "form-control"
          %br
          .action
            = f.submit 'Save', class: "btn btn-md btn-success"


                  

            

app/views/partials/_modal_user_show.html.haml
%button.btn.btn-secondary.btn-sm{"data-target" => "#modal_show#{user.id}", "data-toggle" => "modal", :type => "button"}
  Show
.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "modal_show#{user.id}", :role => "dialog", :tabindex => "-1", :id => "modal_show#{user.id}"}
  .modal-dialog.modal-lg{:role => "document"}
    .modal-content
      .modal-header
        %h2#exampleModalLabel.modal-title.text-center
          - if user.role == 'admin'
            %p.text-center{:style => "color:purple"} 
              = user.username
          - elsif user.role == 'mentor'
            %p.text-center{:style => "color:blue"}
              = user.username
          - else
            %p.text-center{:style => "color:teal"}
              = user.username
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×      
      .modal-body
        .row
          .col-6
            %img{:alt => "Card image cap", :src => "https://robohash.org/#{user.username}.png?size=258x180"}/
          .col-6
            %h5{:style => "color:gray"} Name
            %span
              = "#{user.name}, #{user.lastname}"
            %h5{:style => "color:gray"} Role
            = user.role
            %h5{:style => "color:gray"} Email
            = user.email
          .col-12
            %br
            %h5{:style => "color:gray"} Programming Skills
            = user.knowledge
            %br
            %br
              
        
            


            